[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
contracts.workspace = true
dotenv.workspace = true
ethers.workspace = true
eyre.workspace = true
tokio = { workspace = true, features = ["full"] }
