env_files = [
    "../.env",
]

[tasks.call]
command = "cargo"
args = [
    "run",
    "-q",
    "--bin",
    "call",
]

[tasks.vote]
command = "cargo"
args = [
    "run",
    "-q",
    "--bin",
    "vote",
]

[tasks.verify]
command = "cargo"
args = [
    "run",
    "-q",
    "--bin",
    "verify",
]
