env_files = [
    "../.env",
]

[tasks.check]
command = "cargo"
args = [
    "stylus",
    "check",
]

# See: https://docs.arbitrum.io/stylus/stylus-quickstart
# cargo stylus deploy \
#   --endpoint='http://localhost:8547' \
#   --private-key="0xb6b15c8cb491557369f3c7d2c287b053eb229daa9c22138887752191c9520659"
[tasks.deploy]
command = "cargo"
args = [
    "stylus",
    "deploy",
    "--endpoint=${RPC_URL}",
    "--private-key=${PRIVATE_KEY}",
]

# Run after deploy with updated contract address...
[tasks.cache]
command = "cargo"
args = [
    "stylus",
    "cache",
    "bid",
    "--endpoint=${RPC_URL}",
    "--private-key=${PRIVATE_KEY}",
    "${CONTRACT_ADDRESS}",
    "0",
]

[tasks.abi]
command = "cargo"
args = [
    "stylus",
    "export-abi",
]
